export const redirects: Record<string, string> = {
    // Short vanity redirects — blog post 51 (digital independence)
    '/51/': '/fi/blog/51/digitaalinen-itsenaisyys-on-valttamattomyys/',
    '/51sv/': '/sv/blog/51/digital-sjalvstandighet-ar-en-nodvandighet/',

    // Localised FI/SV static-page slugs (September 2026) — old English-segment URLs
    '/about/': '/fi/laurista/',
    '/about-me/': '/en/about/',

    '/blogi/': '/fi/blog/',
    '/blogi/aanestin-lansiradan-puolesta/': '/fi/blog/46/aanestin-lansiradan-puolesta/',

    '/blogi/aluevaalit2022/': '/fi/kategoria/aluevaalit-2022/',
    '/blogi/aluevaalit2025/': '/fi/kategoria/aluevaalit-2025/',
    '/blogi/digitalisaatio/': '/fi/kategoria/digitalisaatio/',
    '/blogi/ehdolle-aluevaaleihin/': '/fi/blog/7/ehdolle-aluevaaleihin/',
    '/blogi/ehdoton-ei-toisen-asteen-lukukausimaksuille/': '/fi/blog/36/ehdoton-ei-toisen-asteen-lukukausimaksuille/',
    '/blogi/ennen-oli-paremmin/': '/fi/blog/13/ennen-oli-paremmin/',
    '/blogi/esseita-maahanmuutosta-maahanmuuton-maarasta/': '/fi/blog/24/esseita-maahanmuutosta-maahanmuuton-maarasta/',
    '/blogi/hyvin-suunniteltu-on-puoliksi-tehty-mutta/': '/fi/blog/5/hyvin-suunniteltu-on-puoliksi-tehty-mutta/',
    '/blogi/infra/': '/fi/kategoria/infra/',
    '/blogi/jokaisella-on-oikeus-olla-ylpea-olemassaolostaan/':
        '/fi/blog/40/jokaisella-on-oikeus-olla-ylpea-olemassaolostaan/',
    '/blogi/joukkoliikenne-ei-voi-kallistua-loputtomiin/': '/fi/blog/41/joukkoliikenne-ei-voi-kallistua-loputtomiin/',
    '/blogi/kasvava-kunta-tarvitsee-elinvoimaisen-keskustan/':
        '/fi/blog/35/kasvava-kunta-tarvitsee-elinvoimaisen-keskustan/',
    '/blogi/kirkkonummi/': '/fi/kategoria/kirkkonummi/',
    '/blogi/kirkkonummi-lisa-on-sinunkin-etusi/': '/fi/blog/2/kirkkonummi-lisa-on-sinunkin-etusi/',
    '/blogi/kotihoidon-tuen-kuntalisa/': '/fi/blog/1/kotihoidon-tuen-kuntalisa/',
    '/blogi/koulutus-on-kunnan-tarkein-tehtava/': '/fi/blog/37/koulutus-on-kunnan-tarkein-tehtava/',
    '/blogi/koulutusko-erityissuojelussa/': '/fi/blog/27/koulutusko-erityissuojelussa/',
    '/blogi/kuka-paattaa-mista-puhumma/': '/fi/blog/43/kuka-paattaa-mista-puhumme/',
    '/blogi/kunnan-pitaa-suunnitella-pitkajanteisesti/': '/fi/blog/15/kunnan-pitaa-suunnitella-pitkajanteisesti/',
    '/blogi/kuntavaaleissa-ratkaistaan-arjen-asioita/': '/fi/blog/33/kuntavaaleissa-ratkaistaan-arjen-asioita/',

    '/blogi/kuntavaalit-ja-aluevaalit-2025/': '/fi/blog/20/kuntavaalit-ja-aluevaalit-2025/',
    '/blogi/kuntavaalit2025/': '/fi/kategoria/kuntavaalit-2025/',
    '/blogi/kylma-riihi-kirkkonummelle/': '/fi/blog/38/kylma-riihi-kirkkonummelle/',
    '/blogi/lahiluontoa-pitaa-vaalia/': '/fi/blog/12/lahiluontoa-pitaa-vaalia/',
    '/blogi/lansi-uusimaa/': '/fi/kategoria/lansi-uusimaa/',
    '/blogi/lansirata/': '/fi/kategoria/lansirata/',
    '/blogi/lansirata-paatos-nosti-esiin-ongelmia-kirkkonummen-pitkajanteisessa-strategisessa-kehittamisessa/':
        '/fi/blog/50/lansirata-paatos-nosti-esiin-ongelmia-kirkkonummen-pitkajanteisessa-strategisessa-kehittamisessa/',
    '/blogi/lapsista-saastaminen-ei-kannata/': '/fi/blog/19/lapsista-saastaminen-ei-kannata/',
    '/blogi/liikenne/': '/fi/kategoria/liikenne/',
    '/blogi/luontomme-on-valttimme-vuodesta-toiseen/': '/fi/blog/17/luontomme-on-valttimme-vuodesta-toiseen/',
    '/blogi/luulo-ei-ole-tiedon-vaarti/': '/fi/blog/34/luulo-ei-ole-tiedon-vaarti/',
    '/blogi/maahanmuutto/': '/fi/kategoria/maahanmuutto/',
    '/blogi/maahanmuuttokeskustelusta/': '/fi/blog/23/maahanmuuttokeskustelusta/',
    '/blogi/mita-jos-terveyskeskusta-ei-olisikaan/': '/fi/blog/9/mita-jos-terveyskeskusta-ei-olisikaan/',
    '/blogi/myytteja-maahanmuutosta/': '/fi/blog/42/myytteja-maahanmuutosta/',
    '/blogi/onnea-suomi/': '/fi/blog/25/onnea-suomi/',
    '/blogi/opetus/': '/fi/kategoria/opetus/',
    '/blogi/osuuskauppavaalit/': '/fi/kategoria/osuuskauppavaalit/',
    '/blogi/osuuskauppavaalit-koskettavat-meita-kaikkia/': '/fi/blog/18/osuuskauppavaalit-koskettavat-meita-kaikkia/',
    '/blogi/paivakodit-kaipaavat-opettajia/': '/fi/blog/6/paivakodit-kaipaavat-opettajia/',
    '/blogi/passien-biometristen-tunnisteiden-kayttoa-ei-pida-laajentaa/':
        '/fi/blog/48/passien-biometristen-tunnisteiden-kayttoa-ei-pida-laajentaa/',
    '/blogi/perhesiteeseen-perustuvasta-maahanmuutosta/': '/fi/blog/26/perhesiteeseen-perustuvasta-maahanmuutosta/',
    '/blogi/perusoikeuksia-ei-pida-purkaa-perusteettomasti/':
        '/fi/blog/45/perusoikeuksia-ei-pida-purkaa-perusteettomasti/',
    '/blogi/perusturvajaosto-mika-se-on/': '/fi/blog/8/perusturvajaosto-mika-se-on/',
    '/blogi/puheilla-muovaamme-todellisuutta/': '/fi/blog/14/puheilla-muovaamme-todellisuutta/',
    '/blogi/sivistyksen-talo-lyyra-avaa-uusia-mahdollisuuksia-ja-nayttaa-suuntaa/':
        '/fi/blog/49/sivistyksen-talo-lyyra-avaa-uusia-mahdollisuuksia-ja-nayttaa-suuntaa/',
    '/blogi/sosiaalinen-media/': '/fi/kategoria/sosiaalinen-media/',
    '/blogi/sote-on-hyvinvointiyhteiskunnan-kulmakivi/': '/fi/blog/10/sote-on-hyvinvointiyhteiskunnan-kulmakivi/',
    '/blogi/soteuudistus/': '/fi/kategoria/sote-uudistus/',
    '/blogi/tasa-arvo-ja-yhdenvertaisuus/': '/fi/kategoria/tasa-arvo/',
    '/blogi/teknologia/': '/fi/kategoria/teknologia/',
    '/blogi/tekoaly/': '/fi/kategoria/tekoaly/',
    '/blogi/tekoaly-ei-pysty-mihin-tahansa/': '/fi/blog/44/tekoaly-ei-pysty-mihin-tahansa/',
    '/blogi/terveys-kuuluu-kaikille/': '/fi/blog/11/terveys-kuuluu-kaikille/',
    '/blogi/turvapaikan-saaneista/': '/fi/blog/30/turvapaikan-saaneista/',
    '/blogi/turvapaikanhakijoista/': '/fi/blog/31/turvapaikanhakijoista/',
    '/blogi/tyoperaisesta-maahanmuutosta/': '/fi/blog/28/tyoperaisesta-maahanmuutosta/',
    '/blogi/ulkomailta-opiskelemaan-tulleista/': '/fi/blog/29/ulkomailta-opiskelemaan-tulleista/',
    '/blogi/uusi-vuosi-tuttu-talvikunnossapito/': '/fi/blog/16/uusi-vuosi-tuttu-talvikunnossapito/',
    '/blogi/valtuustoaloite/': '/fi/kategoria/valtuustoaloite/',
    '/blogi/valtuustoaloite-vuosittainen-pride-liputus-kirkkonummelle/':
        '/fi/blog/39/valtuustoaloite-vuosittainen-pride-liputus-kirkkonummelle/',
    '/blogi/varhaiskasvatuksen-kerhotoiminta/': '/fi/blog/3/varhaiskasvatuksen-kerhotoiminta/',
    '/blogi/varhaiskasvatuksen-riittavyydesta-ei-saa-tinkia/':
        '/fi/blog/4/varhaiskasvatuksen-riittavyydesta-ei-saa-tinkia/',
    '/blogi/varhaiskasvatus/': '/fi/kategoria/varhaiskasvatus/',
    '/blogi/vastuu-on-meidan-aikuisten/': '/fi/blog/21/vastuu-on-meidan-aikuisten/',
    '/blogi/vuosi-2026-on-tekoalyn/': '/fi/blog/47/vuosi-2026-on-tekoalyn/',
    '/blogi/yhdessa-olemme-vahvempia/': '/fi/blog/32/yhdessa-olemme-vahvempia/',
    '/blogi/yksi-askel-eteen-kaksi-taakse/': '/fi/blog/22/yksi-askel-eteen-kaksi-taakse/',
    '/blogi/yksityisyydensuoja/': '/fi/kategoria/yksityisyydensuoja/',
    '/contact/': '/fi/yhteystiedot/',
    // Issue #1077 — wrong-locale slug redirects (Google-indexed 404s)
    '/en/blog/16/uusi-vuosi-tuttu-talvikunnossapito/': '/en/blog/16/new-year-familiar-winter-maintenance/',
    '/en/blog/17/luontomme-on-valttimme-vuodesta-toiseen/': '/en/blog/17/our-nature-is-our-trump-card-year-after-year/',
    '/en/blog/46/aanestin-lansiradan-puolesta/': '/en/blog/46/i-voted-for-the-western-rail-link/',
    '/en/blog/48/passien-biometristen-tunnisteiden-kayttoa-ei-pida-laajentaa/':
        '/en/blog/48/the-use-of-biometric-identifiers-in-passports-must-not-be-expanded/',
    '/en/blog/52/kirkkonummi-on-tanaan-tasa-arvoisempi-kuin-eilen/':
        '/en/blog/52/kirkkonummi-is-more-equal-today-than-yesterday/',
    '/en/blog/56/lahteela-yhteinen-helmi-kirkkonummen-rannikolla/': '/en/blog/56/lahteela-a-gem-on-kirkkonummis-coast/',
    // Issue #1058 — English tag ID redirects (old Finnish category URLs → new English ones)
    '/en/category/aluevaalit2022/': '/en/category/regional-elections-2022/',
    '/en/category/aluevaalit2025/': '/en/category/regional-elections-2025/',
    '/en/category/digitaalinen-itsenaisyys/': '/en/category/digital-independence/',
    '/en/category/digitalisaatio/': '/en/category/digitalisation/',
    '/en/category/infra/': '/en/category/infrastructure/',
    '/en/category/kaavoitus/': '/en/category/urban-planning/',
    '/en/category/kuntavaalit2025/': '/en/category/municipal-elections-2025/',
    '/en/category/lansi-uusimaa/': '/en/category/western-uusimaa/',
    '/en/category/lansirata/': '/en/category/west-railway/',
    '/en/category/learning/': '/en/category/enlightenment/',
    '/en/category/liikenne/': '/en/category/transportation/',
    '/en/category/maahanmuutto/': '/en/category/immigration/',
    '/en/category/opetus/': '/en/category/education/',
    '/en/category/osuuskauppavaalit/': '/en/category/coop-elections/',
    '/en/category/perusturva/': '/en/category/basic-welfare/',
    '/en/category/sivistys/': '/en/category/culture-and-education/',
    '/en/category/sosiaalinen-media/': '/en/category/social-media/',
    '/en/category/soteuudistus/': '/en/category/health-and-social-reform/',
    '/en/category/tasa-arvo-ja-yhdenvertaisuus/': '/en/category/equality-and-non-discrimination/',
    '/en/category/teknologia/': '/en/category/technology/',
    '/en/category/tekoaly/': '/en/category/artificial-intelligence/',
    '/en/category/valtuustoaloite/': '/en/category/council-motion/',
    '/en/category/varhaiskasvatus/': '/en/category/early-childhood-education/',
    '/en/category/yksityisyydensuoja/': '/en/category/privacy/',
    // Issue #1288 — topics merged into blog
    '/en/topics/': '/en/blog/',
    '/fi/about/': '/fi/laurista/',
    '/fi/blog/25/congratulations-finland/': '/fi/blog/25/onnea-suomi/',
    // id 43 fi slug typo fix (puhumma → puhumme)
    '/fi/blog/43/kuka-paattaa-mista-puhumma/': '/fi/blog/43/kuka-paattaa-mista-puhumme/',
    // Issue #1058 — Finnish category URL fixes
    '/fi/category/aluevaalit2022/': '/fi/kategoria/aluevaalit-2022/',
    '/fi/category/aluevaalit2025/': '/fi/kategoria/aluevaalit-2025/',
    '/fi/category/digitaalinen-itsenaisyys/': '/fi/kategoria/digitaalinen-itsenaisyys/',
    '/fi/category/digitalisaatio/': '/fi/kategoria/digitalisaatio/',
    '/fi/category/infra/': '/fi/kategoria/infra/',
    '/fi/category/kaavoitus/': '/fi/kategoria/kaavoitus/',
    '/fi/category/kuntavaalit2025/': '/fi/kategoria/kuntavaalit-2025/',
    '/fi/category/lansi-uusimaa/': '/fi/kategoria/lansi-uusimaa/',
    '/fi/category/lansirata/': '/fi/kategoria/lansirata/',
    '/fi/category/learning/': '/fi/kategoria/sivistys/',
    '/fi/category/liikenne/': '/fi/kategoria/liikenne/',
    '/fi/category/maahanmuutto/': '/fi/kategoria/maahanmuutto/',
    '/fi/category/opetus/': '/fi/kategoria/opetus/',
    '/fi/category/osuuskauppavaalit/': '/fi/kategoria/osuuskauppavaalit/',
    '/fi/category/perusturva/': '/fi/kategoria/perusturva/',
    '/fi/category/sivistys/': '/fi/kategoria/kulttuuri/',
    '/fi/category/sosiaalinen-media/': '/fi/kategoria/sosiaalinen-media/',
    '/fi/category/soteuudistus/': '/fi/kategoria/sote-uudistus/',
    '/fi/category/tasa-arvo-ja-yhdenvertaisuus/': '/fi/kategoria/tasa-arvo/',
    '/fi/category/teknologia/': '/fi/kategoria/teknologia/',
    '/fi/category/tekoaly/': '/fi/kategoria/tekoaly/',
    '/fi/category/valtuustoaloite/': '/fi/kategoria/valtuustoaloite/',
    '/fi/category/varhaiskasvatus/': '/fi/kategoria/varhaiskasvatus/',
    '/fi/category/yksityisyydensuoja/': '/fi/kategoria/yksityisyydensuoja/',
    '/fi/contact/': '/fi/yhteystiedot/',
    '/fi/newsletter/': '/fi/uutiskirje/',
    '/fi/privacy-policy/': '/fi/tietosuoja/',
    '/fi/recommendations/': '/fi/suositukset/',
    // Issue #1288 — topics merged into blog
    '/fi/topics/': '/fi/blog/',
    '/kategoria/aluevaalit2022/': '/fi/kategoria/aluevaalit-2022/',
    '/kategoria/aluevaalit2025/': '/fi/kategoria/aluevaalit-2025/',
    '/kategoria/digitaalinen-itsenaisyys/': '/fi/kategoria/digitaalinen-itsenaisyys/',
    '/kategoria/digitalisaatio/': '/fi/kategoria/digitalisaatio/',
    '/kategoria/infra/': '/fi/kategoria/infra/',
    '/kategoria/kaavoitus/': '/fi/kategoria/kaavoitus/',
    '/kategoria/kirkkonummi/': '/fi/kategoria/kirkkonummi/',
    '/kategoria/kuntavaalit2025/': '/fi/kategoria/kuntavaalit-2025/',
    '/kategoria/lansi-uusimaa/': '/fi/kategoria/lansi-uusimaa/',
    '/kategoria/lansirata/': '/fi/kategoria/lansirata/',
    '/kategoria/liikenne/': '/fi/kategoria/liikenne/',
    '/kategoria/maahanmuutto/': '/fi/kategoria/maahanmuutto/',
    '/kategoria/opetus/': '/fi/kategoria/opetus/',
    '/kategoria/osuuskauppavaalit/': '/fi/kategoria/osuuskauppavaalit/',
    '/kategoria/perusturva/': '/fi/kategoria/perusturva/',
    '/kategoria/sivistys/': '/fi/kategoria/kulttuuri/',
    '/kategoria/sosiaalinen-media/': '/fi/kategoria/sosiaalinen-media/',
    '/kategoria/sosiaalinenMedia/': '/fi/kategoria/sosiaalinen-media/',
    '/kategoria/soteuudistus/': '/fi/kategoria/sote-uudistus/',
    '/kategoria/tasa-arvo-ja-yhdenvertaisuus/': '/fi/kategoria/tasa-arvo/',
    '/kategoria/teknologia/': '/fi/kategoria/teknologia/',
    '/kategoria/tekoaly/': '/fi/kategoria/tekoaly/',
    '/kategoria/valtuustoaloite/': '/fi/kategoria/valtuustoaloite/',
    '/kategoria/varhaiskasvatus/': '/fi/kategoria/varhaiskasvatus/',
    '/kategoria/yksityisyydensuoja/': '/fi/kategoria/yksityisyydensuoja/',
    // Issue #1078 — top-level election campaign page redirects
    '/kommunalvalet-och-valfardsomradesvalet-2025/': '/sv/blog/20/kommun-och-valfardsvalet-2025/',
    '/kuntavaalit-ja-aluevaalit-2025/': '/fi/blog/20/kuntavaalit-ja-aluevaalit-2025/',
    '/minusta/': '/fi/laurista/',
    '/municipal-elections-and-county-elections-2025/': '/en/blog/20/municipal-and-regional-elections-2025/',
    '/newsletter/': '/fi/uutiskirje/',
    '/om-mig/': '/sv/om-lauri/',
    '/ota-yhteytta/': '/fi/yhteystiedot/',
    '/privacy-policy/': '/fi/tietosuoja/',
    '/recommendations/': '/fi/suositukset/',
    '/sv/about/': '/sv/om-lauri/',
    // Issue #1077 — wrong-locale slug redirects (Google-indexed 404s)
    '/sv/blog/14/puheilla-muovaamme-todellisuutta/': '/sv/blog/14/med-ord-formar-vi-verkligheten/',
    '/sv/blog/15/kunnan-pitaa-suunnitella-pitkajanteisesti/': '/sv/blog/15/kommunen-maste-planera-langsiktigt/',
    '/sv/blog/18/osuuskauppavaalit-koskettavat-meita-kaikkia/': '/sv/blog/18/vbo-valen-beror-oss-alla/',
    '/sv/blog/46/aanestin-lansiradan-puolesta/': '/sv/blog/46/jag-rostade-for-vasternabanan/',
    '/sv/blog/48/passien-biometristen-tunnisteiden-kayttoa-ei-pida-laajentaa/':
        '/sv/blog/48/anvandningen-av-biometriska-identifierare-i-pass-far-inte-utvidgas/',
    '/sv/blog/49/sivistyksen-talo-lyyra-avaa-uusia-mahdollisuuksia-ja-nayttaa-suuntaa/':
        '/sv/blog/49/lyyra-bildningens-hus-oppnar-nya-mojligheter-och-visar-vagen/',
    '/sv/blog/51/digitaalinen-itsenaisyys-on-valttamattomyys/':
        '/sv/blog/51/digital-sjalvstandighet-ar-en-nodvandighet/',
    '/sv/blog/52/kirkkonummi-on-tanaan-tasa-arvoisempi-kuin-eilen/':
        '/sv/blog/52/kyrsklatt-ar-mer-jamlikt-idag-an-det-var-igar/',
    '/sv/blog/56/lahteela-yhteinen-helmi-kirkkonummen-rannikolla/':
        '/sv/blog/56/lahteela-en-gemma-vid-kyrkslaendets-kust/',
    // Issue #1058 — Swedish category URL fixes
    '/sv/category/aluevaalit2022/': '/sv/kategori/regionval-2022/',
    '/sv/category/aluevaalit2025/': '/sv/kategori/regionval-2025/',
    '/sv/category/digitaalinen-itsenaisyys/': '/sv/kategori/digital-sjalvstandighet/',
    '/sv/category/digitalisaatio/': '/sv/kategori/digitalisering/',
    '/sv/category/infra/': '/sv/kategori/infrastruktur/',
    '/sv/category/kaavoitus/': '/sv/kategori/planlaggning/',
    '/sv/category/kuntavaalit2025/': '/sv/kategori/kommunalval-2025/',
    '/sv/category/lansi-uusimaa/': '/sv/kategori/vastra-nyland/',
    '/sv/category/lansirata/': '/sv/kategori/vastbanan/',
    '/sv/category/learning/': '/sv/kategori/bildning/',
    '/sv/category/liikenne/': '/sv/kategori/trafik/',
    '/sv/category/maahanmuutto/': '/sv/kategori/invandring/',
    '/sv/category/opetus/': '/sv/kategori/utbildning/',
    '/sv/category/osuuskauppavaalit/': '/sv/kategori/kooperativval/',
    '/sv/category/perusturva/': '/sv/kategori/grundtrygghet/',
    '/sv/category/sivistys/': '/sv/kategori/kultur/',
    '/sv/category/sosiaalinen-media/': '/sv/kategori/sociala-medier/',
    '/sv/category/soteuudistus/': '/sv/kategori/vard-och-servicereform/',
    '/sv/category/tasa-arvo-ja-yhdenvertaisuus/': '/sv/kategori/jamlikhet/',
    '/sv/category/teknologia/': '/sv/kategori/teknologi/',
    '/sv/category/tekoaly/': '/sv/kategori/artificiell-intelligens/',
    '/sv/category/valtuustoaloite/': '/sv/kategori/fullmaktigeinitiativ/',
    '/sv/category/varhaiskasvatus/': '/sv/kategori/smabarnspedagogik/',
    '/sv/category/yksityisyydensuoja/': '/sv/kategori/integritetsskydd/',
    '/sv/contact/': '/sv/kontakt/',
    '/sv/newsletter/': '/sv/nyhetsbrev/',
    '/sv/privacy-policy/': '/sv/dataskydd/',
    '/sv/recommendations/': '/sv/rekommendationer/',
    // Issue #1288 — topics merged into blog
    '/sv/topics/': '/sv/blog/',
}

/**
 * Short URLs for print and social, keyed by their trailing-slash form. Astro gets only that form
 * (a stub per spelling would be two routes for one path, which Astro rejects); `_redirects` also
 * gets the slashless spelling, so neither form takes an extra trailing-slash hop.
 */
export const shortLinks: Record<string, string> = {
    '/vaalirahoitus/': '/fi/eduskuntavaalit/vaalirahoitus/',
}
